"""Add unique constraint to index

Revision ID: 110f5b482ad6
Revises: bec3094271b8
Create Date: 2025-07-19 15:28:37.791226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110f5b482ad6'
down_revision: Union[str, Sequence[str], None] = 'bec3094271b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dshops', ['index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dshops', type_='unique')
    # ### end Alembic commands ###
