"""added columns status and responsed_code

Revision ID: 6d0dcf75b876
Revises: 880029306ae6
Create Date: 2025-07-19 14:53:38.514613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0dcf75b876'
down_revision: Union[str, Sequence[str], None] = '880029306ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dshops', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('dshops', sa.Column('responsed_code', sa.Integer(), nullable=False))
    op.alter_column('dshops', 'shop_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dshops', 'reception_time',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dshops', 'holidays',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dshops', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dshops', 'delivery_person',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dshops', 'delivery_person',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dshops', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dshops', 'holidays',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dshops', 'reception_time',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dshops', 'shop_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('dshops', 'responsed_code')
    op.drop_column('dshops', 'status')
    # ### end Alembic commands ###
