"""make all columns not null except note

Revision ID: 880029306ae6
Revises: 1ee6b88a441d
Create Date: 2025-07-18 17:06:07.102944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880029306ae6'
down_revision: Union[str, Sequence[str], None] = '1ee6b88a441d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dshops', 'index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dshops', 'url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('dshops', 'shop_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dshops', 'reception_time',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dshops', 'holidays',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dshops', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dshops', 'delivery_person',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dshops', 'delivery_person',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dshops', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dshops', 'holidays',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dshops', 'reception_time',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dshops', 'shop_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dshops', 'url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('dshops', 'index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
