"""added columns etag

Revision ID: bec3094271b8
Revises: 6d0dcf75b876
Create Date: 2025-07-19 15:02:07.761445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec3094271b8'
down_revision: Union[str, Sequence[str], None] = '6d0dcf75b876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dshops', sa.Column('etag', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dshops', 'etag')
    # ### end Alembic commands ###
