"""added created_at and updated_at

Revision ID: fc2bf6dbb746
Revises: 110f5b482ad6
Create Date: 2025-07-19 23:02:28.226694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2bf6dbb746'
down_revision: Union[str, Sequence[str], None] = '110f5b482ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dshops', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('dshops', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dshops', 'updated_at')
    op.drop_column('dshops', 'created_at')
    # ### end Alembic commands ###
